let shopItemsData = [
  {
    id: "first",
    name: "Watch-01",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/product1.png",
  },
  {
    id: "second",
    name: "Watch-02",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/product1.png",
  },
  {
    id: "third",
    name: "Watch-03",
    price: 250,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/product1.png",
  },
  {
    id: "fourth",
    name: "Watch-04",
    price: 290,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/product1.png",
  },
  {
    id: "fifth",
    name: "Watch-05",
    price: 700,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new1.png",
  },
  {
    id: "sixth",
    name: "Watch-06",
    price: 320,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new2.png",
  },
  {
    id: "seven",
    name: "Watch-07",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new3.png",
  },
  {
    id: "eight",
    name: "Watch-08",
    price: 250,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new4.png",
  },
  {
    id: "nine",
    name: "Watch-09",
    price: 390,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new4.png",
  },
  {
    id: "ten",
    name: "Watch-07",
    price: 600,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new3.png",
  },
  {
    id: "eleven",
    name: "Watch-08",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new4.png",
  },
  {
    id: "twelve",
    name: "Watch-09",
    price: 800,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/new4.png",
  },
  
];